### ISSUE TITLE
Could you please provide the coco-train-idxs.p file?

### ISSUE THREAD

**Issue by hologerry** [jiasenlu/NeuralBabyTalk#12]
When I try to train the model with `--self_critical True`, encountered such error:
```
load reward function...
Traceback (most recent call last):
  File "main.py", line 283, in <module>
    model = AttModel.TopDownModel(opt)
  File "/data/gaoy/NeuralBabyTalk_self-critical/misc/AttModel.py", line 215, in __init__
    super(TopDownModel, self).__init__(opt)
  File "/data/gaoy/NeuralBabyTalk_self-critical/misc/model.py", line 101, in __init__
    self.get_self_critical_reward = get_self_critical_reward(opt)
  File "/data/gaoy/NeuralBabyTalk_self-critical/misc/rewards.py", line 38, in __init__
    self.CiderD_scorer = CiderD(df=opt.cached_tokens)
  File "tools/pycider/pyciderevalcap/ciderD/ciderD.py", line 28, in __init__
    self.cider_scorer = CiderScorer(n=self._n, df_mode=self._df)
  File "/data/gaoy/NeuralBabyTalk_self-critical/tools/pycider/pyciderevalcap/ciderD/ciderD_scorer.py", line 66, in __init__
    pkl_file = pickle.load(open(os.path.join('data', df_mode + '.p'),'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco-train-idxs.p'
```
the `coco-train-idxs` is the `--cached_tokens` default value, but I'm not sure about what this is ...
Thanks a lot for this repo and your paper.

**Comment by JiayunLi** [comment]
I think you may be able to generate it with prepro_ngrams_bak.py (coco) or prepro_ngrams.py (Flicker30).

**Comment by hologerry** [comment]
OK, Thanks
