### ISSUE TITLE
BUG in misc/utils.py

### ISSUE THREAD

**Issue by wangxinyu0922** [jiasenlu/NeuralBabyTalk#13]
In my environment (pytorch 0.4.0), it will report error for line 78:
word = itow[str(ix)]
Because ix is a tensor, so it is better to use ix.item() to replace the ix, also for line 112, 128 and 154

**Comment by Dvangelion** [comment]
I have a similar bug reported in the training phase. I was wondering I should replace fg_seq[i,j] by fg_seq[i,j].item() as well? Thanks for your help! 

Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f4039abbf50>> ignored
/DATA/Ke/Babytalk/NeuralBabyTalk/misc/model.py:306: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  conv_feats, fc_feats = self.cnn(Variable(img.data, volatile=True))
Traceback (most recent call last):
  File "main.py", line 357, in <module>
    lang_stats = eval(opt)
  File "main.py", line 154, in eval
    seq.data, bn_seq.data, fg_seq.data, opt.vocab_size, opt)
  File "/DATA/Ke/Babytalk/NeuralBabyTalk/misc/utils.py", line 64, in decode_sequence
    det_word = itod[fg_seq[i,j]]
KeyError: tensor(110, device='cuda:0')
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f4039abb050>> ignored

**Comment by wangxinyu0922** [comment]
There are many part having the same problem, you can try it.

**Comment by Erwin-fy** [comment]
@Dvangelion, I meet the same problem, have you solved it ???

**Comment by luulinh90s** [comment]
awwwwwwww, I really hate the deprecation of Python, always and always face conflicts when running python2 code on python3. If i run on python2, somepackages will not be supported. 
Python is painfulllllllll
