### ISSUE TITLE
where is _roi_align?

### ISSUE THREAD

**Issue by heartraeh** [jiasenlu/NeuralBabyTalk#17]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    import misc.AttModel as AttModel
  File "/home/wu/NeuralBabyTalk-master/misc/AttModel.py", line 10, in <module>
    from misc.model import AttModel
  File "/home/wu/NeuralBabyTalk-master/misc/model.py", line 14, in <module>
    from pooling.roi_align.modules.roi_align import RoIAlignAvg
  File "/home/wu/NeuralBabyTalk-master/pooling/roi_align/modules/roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction
  File "/home/wu/NeuralBabyTalk-master/pooling/roi_align/functions/roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "/home/wu/NeuralBabyTalk-master/pooling/roi_align/_ext/roi_align/__init__.py", line 3, in <module>
    from ._roi_align import lib as _lib, ffi as _ffi
ImportError: No module named _roi_align

**Comment by waallf** [comment]
I have similar problem,have you solved it?

**Comment by waallf** [comment]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    import misc.AttModel as AttModel
  File "/home/z840/zhaoxinya/NeuralBabyTalk-master/misc/AttModel.py", line 10, in <module>
    from misc.model import AttModel
  File "/home/z840/zhaoxinya/NeuralBabyTalk-master/misc/model.py", line 14, in <module>
    from pooling.roi_align.modules.roi_align import RoIAlignAvg
  File "/home/z840/zhaoxinya/NeuralBabyTalk-master/pooling/roi_align/modules/roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction
  File "/home/z840/zhaoxinya/NeuralBabyTalk-master/pooling/roi_align/functions/roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "/home/z840/zhaoxinya/NeuralBabyTalk-master/pooling/roi_align/_ext/roi_align/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 14, in <module>
    raise ImportError("torch.utils.ffi requires the cffi package")
ImportError: torch.utils.ffi requires the cffi package

**Comment by heartraeh** [comment]
I think you need to reconfigure the environment

**Comment by shuguohe** [comment]
@heartraeh I have the same issue. Have you resolved the issue?

**Comment by shuguohe** [comment]
@heartraeh solved this issue by run make.sh in the roi_align folder.

**Comment by madnankhalid** [comment]
@shuguohe i am still unable to solve the same problem :(
i also unable to run make.sh file in the roi_align folder,
guide me plase...

**Comment by xjdx123** [comment]
@waallf  I have the same issue. Have you resolved the issue?  I don't know how to solved it now.

**Comment by jiajunhua** [comment]
I have the same issue. Have you resolved the issue? I don't know how to solved it now.
