### ISSUE TITLE
RuntimeError: Only Tensors of floating point dtype can require gradients

### ISSUE THREAD

**Issue by saigequn** [jiasenlu/NeuralBabyTalk#26]
Pytorch 0.4.1、Python2.7、Flickr30k

```
python main.py --path_opt cfgs/normal_flickr_res101.yml --batch_size 20 --cuda True --num_workers 20 --max_epoch 30
```

Traceback (most recent call last):
  File "main.py", line 268, in <module>
    model = AttModel.TopDownModel(opt)
  File "/workspace/mnt/group/ncut-group/saigequn2013/NeuralBabyTalk/misc/AttModel.py", line 214, in __init__
    self.ccr_core = CascadeCore(opt)
  File "/workspace/mnt/group/ncut-group/saigequn2013/NeuralBabyTalk/misc/AttModel.py", line 246, in __init__
    self.fg_mask = Parameter(opt.fg_mask)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parameter.py", line 24, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point dtype can require gradients

**Comment by saigequn** [comment]
self.fg_mask = Parameter(opt.fg_mask.float())

**Comment by luulinh90s** [comment]
its just workaround solution, and it will cause error later.

**Comment by luulinh90s** [comment]
To solve this, change this line:
`self.fg_mask = Parameter(opt.fg_mask)`
to 
`self.fg_mask = Parameter(opt.fg_mask, requires_grad=False)`
and delete the following line.
