### ISSUE TITLE
super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by jack1yang** [jiasenlu/NeuralBabyTalk#32]
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    dataset = DataLoader(opt, split='train')
  File "/workspace/neuralbabytalk/misc/dataloader_coco.py", line 112, in __init__
    self.dataloader_hdf = HDFSingleDataset(self.opt.proposal_h5)
  File "/workspace/neuralbabytalk/misc/dataloader_hdf.py", line 59, in __init__
    super().__init__(
TypeError: super() takes at least 1 argument (0 given)

**Comment by jack1yang** [comment]
because you are using python2.X, you should change super.__init__( ) ,which is ok in python3.X ,into super(HDFSingleDataset,self).__init__ ,and also another one. in NueralBabyTalk/misc/dataloader_hdf.py
