### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by luulinh90s** [jiasenlu/NeuralBabyTalk#35]
```
python main.py --path_opt cfgs/normal_flickr_res101.yml --batch_size 20 --cuda True --num_workers 20 --max_epoch 30
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from misc import utils, eval_utils, AttModel
  File "/home/resl/NeuralBabyTalk/misc/AttModel.py", line 10, in <module>
    from misc.model import AttModel
  File "/home/resl/NeuralBabyTalk/misc/model.py", line 14, in <module>
    from pooling.roi_align.modules.roi_align import RoIAlignAvg
  File "/home/resl/NeuralBabyTalk/pooling/roi_align/modules/roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction
  File "/home/resl/NeuralBabyTalk/pooling/roi_align/functions/roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "/home/resl/NeuralBabyTalk/pooling/roi_align/_ext/roi_align/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/resl/anaconda3/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```

**Comment by luulinh90s** [comment]
To solve this, downgrade your torch version
`pip install torch==0.4.1`

**Comment by phiresky** [comment]
Actually it needs to be `torch==0.4.1.post2` to prevent https://github.com/HazyResearch/metal/issues/101
