### ISSUE TITLE
KeyError: 'caption'

### ISSUE THREAD

**Issue by wlybug** [jiasenlu/NeuralBabyTalk#36]
loading annotations into memory...
Done (t=17.67s)
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    dataset = DataLoader(opt, split='train')
  File "/data/wangly/python3/NeuralBabyTalk/misc/dataloader_coco.py", line 117, in __init__
    self.coco_train = COCO(det_train_path)
  File "tools/sentence_gen_tools/pycocotools/coco.py", line 86, in __init__
    self.process_dataset()
  File "tools/sentence_gen_tools/pycocotools/coco.py", line 298, in process_dataset
    q = ann['caption'].lower()

**Comment by wlybug** [comment]
solved

**Comment by giangnguyen2412** [comment]
When you problem is solved, pls describe it. Its kinda selfish to not share anything when you asked others for help.
