### ISSUE TITLE
ModuleNotFoundError: No module named 'blue_scorer'

### ISSUE THREAD

**Issue by lszp** [jiasenlu/NeuralBabyTalk#48]
Traceback (most recent call last):
  3   File "main.py", line 18, in <module>
  4     from misc import utils, eval_utils, AttModel
  5   File "/home/zhangpan/image_caption/NeuralBabyTalk/misc/utils.py", line 27, in <module>
  6     from coco_eval import score_dcc
  7   File "tools/sentence_gen_tools/coco_eval.py", line 9, in <module>
  8     from pycocoevalcap.bleu.bleu import Bleu
  9   File "tools/coco-caption/pycocoevalcap/bleu/bleu.py", line 11, in <module>
 10     from bleu_scorer import BleuScorer
 11 ModuleNotFoundError: No module named 'bleu_scorer'

**Comment by yuan93427** [comment]
@lszp 
I meet the same issue with you
have you solved this issue?
how to solved it?
