### ISSUE TITLE
Why does _roi_align.so appear some problems?

### ISSUE THREAD

**Issue by jiajunhua** [jiasenlu/NeuralBabyTalk#57]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from misc import utils, eval_utils, AttModel
  File "D:\PycharmProjects\NeuralBabyTalk-master\misc\AttModel.py", line 10, in <module>
    from misc.model import AttModel
  File "D:\PycharmProjects\NeuralBabyTalk-master\misc\model.py", line 14, in <module>
    from pooling.roi_align.modules.roi_align import RoIAlignAvg
  File "D:\PycharmProjects\NeuralBabyTalk-master\pooling\roi_align\modules\roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction
  File "D:\PycharmProjects\NeuralBabyTalk-master\pooling\roi_align\functions\roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "D:\PycharmProjects\NeuralBabyTalk-master\pooling\roi_align\_ext\roi_align\__init__.py", line 3, in <module>
    from ._roi_align import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'pooling.roi_align._ext.roi_align._roi_align'

**Comment by lycutter** [comment]
Hello @jiajunhua , did you solve this problem? I have met this issue just now.
