### ISSUE TITLE
subprocess.CalledProcessError: when calculating SPICE score 

### ISSUE THREAD

**Issue by xmengli999** [jiasenlu/NeuralBabyTalk#9]
Thanks for your excellent work. 
I encountered an error when Evaluating the model.
Is this due to the java version difference? I pasted the log here and thanks for your help in advance!

computing Rouge score...
ROUGE_L: 0.556
computing CIDEr score...
CIDEr: 1.072
computing SPICE score...
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/anu/spice/SpiceScorer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Traceback (most recent call last):
  File "main.py", line 357, in <module>
    lang_stats = eval(opt)
  File "main.py", line 171, in eval
    lang_stats = utils.language_eval(opt.dataset, predictions, str(1), opt.val_split, opt)
  File "/home/xmli/pheng4/NeuralBabyTalk-master/misc/utils.py", line 346, in language_eval
    cocoEval.evaluate()
  File "tools/coco-caption/pycocoevalcap/eval.py", line 52, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "tools/coco-caption/pycocoevalcap/spice/spice.py", line 70, in compute_score
    cwd=os.path.dirname(os.path.abspath(__file__)))
  File "/home/xmli/anaconda2/envs/python2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/home/xmli/pheng4/NeuralBabyTalk-master/tools/coco-caption/pycocoevalcap/spice/tmp/tmp24yYGr', '-cache', '/home/xmli/pheng4/NeuralBabyTalk-master/tools/coco-caption/pycocoevalcap/spice/cache', '-out', '/home/xmli/pheng4/NeuralBabyTalk-master/tools/coco-caption/pycocoevalcap/spice/tmp/tmpXKJqac', '-subset', '-silent']' returned non-zero exit status 1

**Comment by jiasenlu** [comment]
Seems you didn't download the Stanfordcorenlp package. you need to follow the instruction of the SPICE evaluation metric first.

**Comment by jiasenlu** [comment]
You will first need to download the Stanford CoreNLP 3.6.0 code and models for use by SPICE. To do this, run: ./get_stanford_models.sh

**Comment by jiasenlu** [comment]
you can find here

https://github.com/jiasenlu/coco-caption/blob/master/get_stanford_models.sh

**Comment by LibertFan** [comment]
I met the same problem. My spice suddenly broke down and raised the same error exception. Have you fixed the error?

**Comment by fortunechen** [comment]
> I met the same problem. My spice suddenly broke down and raised the same error exception. Have you fixed the error?

me too

**Comment by jiasenlu** [comment]
maybe there are some issues caused by the version update. I haven't work in this area for a long time so I can not provide instant useful suggestions. Could you check the original repo of Spice (https://github.com/peteanderson80/coco-caption) and see whether that one is working?

**Comment by HN123-123** [comment]
I met the same problem. Have you fixed the error?

**Comment by asif-hanif** [comment]
Problem seems to be related updated version of Java. I was using JDK-21 and it result in error while computing SPICE metric.
I later used [Java SE Development Kit 8u391](https://www.oracle.com/java/technologies/downloads/) and error disappeared.

**Comment by fawazsammani** [comment]
If you are on Linux:

```
sudo apt update
sudo apt install openjdk-11-jdk
```

then update the setting such that version 11 is used 
`sudo update-alternatives --config java`
